version: '3.4'

services:
  techchallenge:
    image: ${DOCKER_REGISTRY-}techchallenge/lanchonete:dev
    container_name: lanchonete-app
    build:
      context: ../
      dockerfile: src/Dockerfile
    networks:
      - techchallenge-bridge
    ports:
      - "1443:443"
    expose:
      - 1443 
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: 'mongodb'
    networks:
      - techchallenge-bridge
    ports:
      - "27017:27017"
    expose:
      - 27017

networks:
  techchallenge-bridge:
   driver: bridge